name: use-custom-action
on: [workflow_dispatch]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: use the custom action to greet the user
        id: greeting
        uses: Romany-GL/custom-actions@v1.1
        with:
          your-name: Rooma
      - name: print the output from action
        run: echo  " the time was  ${{ steps.greeting.outputs.time }}"
